name: GitHub Actions

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - 18
          - 20
          - 22
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js v${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
      - name: Install frontend dependencies
        run: npm ci
        working-directory: ./frontend
      - name: Build frontend
        run: npm run build
        working-directory: ./frontend
      # - name: Run tests
      #   run: npm test
      #   working-directory: ./frontend

  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
      - name: Install frontend dependencies
        run: npm ci
        working-directory: ./frontend
      - name: Run checks
        run: npm run check
        working-directory: ./frontend

